# Generated by Django 5.2.11 on 2026-02-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ip_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestlog",
            name="product_id",
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
    ]
