# Generated by Django 5.2.10 on 2026-01-27 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_email_verification_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email_verification_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_verification_token_created",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_verified",
        ),
    ]
