# Generated by Django 5.2.10 on 2026-02-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_customuser_email_verification_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable or disable maintenance mode"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default="We are currently performing scheduled maintenance. We'll be back soon!",
                        help_text="Message to show to users during maintenance",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Maintenance Mode",
                "verbose_name_plural": "Maintenance Mode",
            },
        ),
    ]
