# Generated by Django 5.2.11 on 2026-02-08 04:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_maintenancemode"),
    ]

    operations = []
