# Generated by Django 5.2.11 on 2026-07-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_seed_initial_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="banner_image",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
