# Generated by Django 5.2.11 on 2026-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_category_banner_image_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
    ]
